######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 21 23:34:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h breakout.h brick.h paddle.h
SOURCES += ball.cpp breakout.cpp brick.cpp main.cpp paddle.cpp
