######################################################################
# Automatically generated by qmake (2.01a) Sat May 4 08:18:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h karenina.h mainwindow.h simplemenu.h
FORMS += mainwindow.ui
SOURCES += calculator.cpp karenina.cpp main.cpp mainwindow.cpp simplemenu.cpp
